spring:
  datasource:
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ecommerceapp
    password: ecommerceapp
  data:
    rest:
      base-path: /api
      detection-strategy: ANNOTATED # only repos annotated with @RepositoryRestResource will be visible

allowed:
  origins: https://localhost:4200

okta:
  oauth2:
    client-id: 0oa6ehzr5hmJqbIV95d7
    client-secret: mAVlRpW6McJOCOgSv6NdXWgnIxp0tQq-UQ8P0B_R
    issuer: https://dev-61774659.okta.com/oauth2/default

#####
#
# HTTPS configuration (based on the keytool command that we did just before this)
#
#####

server:
  port: 8443 # Server web port
#  port: 9898 # QA port demo
  ssl:
    enabled: true # Enable HTTPS support (only accept HTTPS requests)
    key-alias: luv2code # Alias that identifies the key in the key store
    key-store: classpath:luv2code-keystore.p12 # Keystore location
    key-store-password: secret # Keystore password
    key-store-type: PKCS12 # Keystore format

#####
#
# Payment processing with Stripe
#
#####

stripe:
  key:
    secret: sk_test_51Ib1gKSFU2UeFkhAsVeatYhqXikj0ufX5qqptrFumS9OYFg0o4KjczOmR80XAe9pJPBnJ8a1KZDT3KfZ5NJn4rgu00YdAbytUB
